python run_idac.py \
--ExpID test2 \
--device "cuda:0" \
--alpha 0.5 \
--use_automatic_entropy_tuning 0 \
--env_name "Hopper-v2" &
python run_idac.py \
--ExpID test2 \
--device "cuda:1" \
--alpha 0.2 \
--use_automatic_entropy_tuning 0 \
--env_name "HalfCheetah-v2" &
python run_idac.py \
--ExpID test2 \
--device "cuda:2" \
--alpha 0.5 \
--use_automatic_entropy_tuning 0 \
--env_name "Humanoid-v2" &
python run_idac.py \
--ExpID test2 \
--device "cuda:3" \
--alpha 0.5 \
--use_automatic_entropy_tuning 0 \
--env_name "Walker2d-v2"
